### ISSUE TITLE
Scrollbar Bug on mat-tab-body-content element

### ISSUE THREAD

**Issue by Fr13dr1ch** [chronikum/nachbarschaftschallenge#4]
- Seems a scrollbar on x axis
![scrollbar_bug](https://user-images.githubusercontent.com/49789636/76638053-1c017980-654c-11ea-824f-8b4c4317479c.png)

**Comment by knirpsfass** [comment]
Liegt an der row im mat-card element
Fix:`    <mat-card>
      <div class="row"> ...</div>
</mat-card>
`

**Comment by Fr13dr1ch** [comment]
Fixed with new Design
